/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Physical AI & Humanoid Robotics Textbook',
    },

    // Module 1
    {
      type: 'category',
      label: 'Module 1: ROS 2 Nervous System',
      link: { type: 'doc', id: 'module1-ros2-nervous-system/index' },
      items: [{ type: 'autogenerated', dirName: 'module1-ros2-nervous-system' }],
    },

    // Module 2
    {
      type: 'category',
      label: 'Module 2: Digital Twin Simulation',
      link: { type: 'doc', id: 'module2-digital-twin-simulation/index' },
      items: [{ type: 'autogenerated', dirName: 'module2-digital-twin-simulation' }],
    },

    // Module 3
    {
      type: 'category',
      label: 'Module 3: AI Brain (NVIDIA Isaac)',
      link: { type: 'doc', id: 'module3-ai-brain-isaac/index' },
      items: [{ type: 'autogenerated', dirName: 'module3-ai-brain-isaac' }],
    },

    // Module 4
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action Robotics',
      link: { type: 'doc', id: 'module4-vla-robotics/index' },
      items: [{ type: 'autogenerated', dirName: 'module4-vla-robotics' }],
    },

    // Capstone Project
    {
      type: 'category',
      label: 'Capstone Project',
      link: { type: 'doc', id: 'capstone-project/chapter1' },
      items: [{ type: 'autogenerated', dirName: 'capstone-project' }],
    },

    // Additional Materials
    {
      type: 'category',
      label: 'Additional Materials',
      link: { type: 'doc', id: 'additional-materials/index' },
      items: [{ type: 'autogenerated', dirName: 'additional-materials' }],
    },

    // Weekly Roadmap
    {
      type: 'category',
      label: 'Weekly Roadmap',
      link: { type: 'doc', id: 'weekly-roadmap' },
      items: [],            // If you want chapters, tell me your folder name
    },
  ],
};

module.exports = sidebars;


